SET SERVEROUTPUT ON;
DECLARE
ROW_COUNT NUMBER(10);

BEGIN


    SELECT count(*) into ROW_COUNT FROM user_tables where table_name = 'CONFIG_TABLE';
    IF(ROW_COUNT > 0)
    THEN
        DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE ALREADY EXISTS');
    ELSE
        EXECUTE IMMEDIATE 'CREATE TABLE CONFIG_TABLE
    (
       TABLE_NAME varchar2(50), 
       TABLE_DEF varchar2(3000) NOT NULL, 
       CONSTRAINT CONFIG_TABLE_PK PRIMARY KEY(TABLE_NAME)
    )
    ';    
     DBMS_OUTPUT.PUT_LINE('TABLE CONFIG_TABLE CREATED SUCCESSFULLY');
    
    EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('LOCATION','CREATE TABLE LOCATION
            (	
            LOCATION_ID NUMBER(10), 
            CITY VARCHAR2(20) NOT NULL, 
            STATE VARCHAR2(20) NOT NULL,
            ZIPCODE NUMBER(10),
            CONSTRAINT LOCATION_PK PRIMARY KEY(LOCATION_ID)
            )
    ')]';
    
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('GROUPS','CREATE TABLE GROUPS
            (	
            GROUPS_ID NUMBER(10), 
            GROUPS_NAME VARCHAR2(20) NOT NULL, 
            GROUPS_DESCRIPTION VARCHAR2(20) NOT NULL,
            CONSTRAINT GROUPS_PK PRIMARY KEY(GROUPS_ID)
            )
    ')]';
    
      EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('ROLES','CREATE TABLE ROLES
            (	
            ROLES_ID NUMBER(10), 
            ROLES_DESCRIPTION VARCHAR2(20) NOT NULL,
            CONSTRAINT ROLES_PK PRIMARY KEY(ROLES_ID)
            )
    ')]';
    
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('GROUPS_ROLES','CREATE TABLE GROUPS_ROLES
            (
             GROUPS_ROLES_ID NUMBER(10), 
             GROUPS_ID NUMBER(10), 
             ROLES_ID NUMBER(10), 
             CONSTRAINT GROUPS_ROLES_PK PRIMARY KEY(GROUPS_ROLES_ID),
             CONSTRAINT GROUPS_ROLES_FK_GROUPS FOREIGN KEY (GROUPS_ID) REFERENCES GROUPS(GROUPS_ID),
             CONSTRAINT GROUPS_ROLES_FK_ROLES FOREIGN KEY (ROLES_ID) REFERENCES ROLES(ROLES_ID) 
    )
    ')]';

    
     EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('USERS','CREATE TABLE USERS
            (
              USER_ID NUMBER(10)
            , PHONE NUMBER(10)
            , PWD VARCHAR2(10) NOT NULL 
            , EMERGENCY_CONTACT VARCHAR2(10) NOT NULL 
            , LOCATION_ID NUMBER(10) NOT NULL 
            , RISK_STATUS INT 
            , LAST_NAME VARCHAR2(10) 
            , FIRST_NAME VARCHAR2(10) NOT NULL 
            , DOB DATE NOT NULL 
            , JOIN_DATE DATE DEFAULT SYSDATE
            , GROUPS_ID NUMBER(10) DEFAULT 1 
            , EMAIL VARCHAR2(10) NOT NULL 
            ,  CONSTRAINT USERS_PK PRIMARY KEY(USER_ID)
            ,  CONSTRAINT EMAIL_VALIDATION CHECK(REGEXP_LIKE(EMAIL,''^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$''))
            ,  CONSTRAINT PHONE_VALIDATION CHECK(REGEXP_LIKE(PHONE, ''^[0-9]{10}$''))
            ,  CONSTRAINT USERS_FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
            ,  CONSTRAINT USERS_FK_GROUPS FOREIGN KEY (GROUPS_ID) REFERENCES GROUPS(GROUPS_ID) 
            )
       ')]';

	EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('TEST_CENTER','CREATE TABLE TEST_CENTER
            (
             TEST_CENTER_ID NUMBER(10), 
             CENTER_NAME VARCHAR2(20) NOT NULL, 
             LOCATION_ID NUMBER(10) NOT NULL, 
	     CENTER_HEAD NUMBER(10) NOT NULL, 
             CONSTRAINT TEST_CENTER_PK PRIMARY KEY(TEST_CENTER_ID),
             CONSTRAINT TEST_CENTER_FK_LOCATION FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
             CONSTRAINT TEST_CENTER_FK_USERS FOREIGN KEY (CENTER_HEAD) REFERENCES USERS(USER_ID) 
    )
    ')]';
	EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('SLOTS,'CREATE TABLE SLOTS
            (
             SLOT_ID NUMBER(10), 
             SLOT_NAME VARCHAR2(20) NOT NULL, 
             SLOT_TIME DATE NOT NULL, 
	     SLOTS_AVAILABLE NUMBER(10) NOT NULL, 
             CONSTRAINT SLOTS_PK PRIMARY KEY(SLOT_ID)
    )
    ')]';
EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('TEST_TYPE,'CREATE TABLE TEST_TYPE
            (
             TEST_TYPE_ID NUMBER(10), 
             TEST_TYPE VARCHAR2(20) NOT NULL,
             CONSTRAINT TEST_TYPE_PK PRIMARY KEY(TEST_TYPE_ID)
    )
    ')]';
       EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('TEST_AVAILABILITY','CREATE TABLE TEST_AVAILABILITY
            (
             TEST_AVAILABILITY_ID NUMBER(10), 
             TEST_CENTER_ID NUMBER(10) NOT NULL, 
             SLOT_ID NUMBER(10) NOT NULL, 
	     TEST_TYPE_ID NUMBER(10) NOT NULL, 
             CONSTRAINT TEST_AVAILABILITY_PK PRIMARY KEY(TEST_AVAILABILITY_ID),
	    CONSTRAINT TEST_AVAILABILITY_FK_ TEST_CENTER FOREIGN KEY (TEST_CENTER_ID) REFERENCES TEST_CENTER(TEST_CENTER_ID),
             CONSTRAINT TEST_AVAILABILITY_SLOTS FOREIGN KEY (SLOT_ID) REFERENCES SLOTS(SLOT_ID),
	    CONSTRAINT TEST_AVAILABILITY_FK_TEST_TYPE FOREIGN KEY (TEST_TYPE_ID) REFERENCES SLOTS(TEST_TYPE_ID)
    )
    ')]';
EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('STAFF_TIMESHEET','CREATE TABLE STAFF_TIMESHEET
            (
             STAFF_TIMESHEET_ID NUMBER(10), 
             USER_ID NUMBER(10) NOT NULL, 
             TEST_CENTER_ID NUMBER(10) NOT NULL, 
	     SLOT_ID NUMBER(10) NOT NULL, 
             CONSTRAINT STAFF_TIMESHEET_PK PRIMARY KEY(STAFF_TIMESHEET_ID),
	CONSTRAINT STAFF_TIMESHEET_FK_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
 	CONSTRAINT STAFF_TIMESHEET_FK_ TEST_CENTER FOREIGN KEY (TEST_CENTER_ID) REFERENCES TEST_CENTER(TEST_CENTER_ID),
	    CONSTRAINT STAFF_TIMESHEET_FK_SLOTS FOREIGN KEY (SLOT_ID) REFERENCES SLOTS(SLOT_ID)
    )
    ')]';
EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('QUARANTINE_FACILITY','CREATE TABLE QUARANTINE_FACILITY
            (
             QUARANTINE_FACILITY_ID NUMBER(10), 
             QUARANTINE_FACILITY_NAME VARCHAR2(20) NOT NULL, 
             ROOMS_AVAILABILITY NUMBER(10) NOT NULL, 
	     DOCTOR_ID NUMBER(10) NOT NULL, 
             CONSTRAINT QUARANTINE_FACILITY_PK PRIMARY KEY(QUARANTINE_FACILITY_ID),
	CONSTRAINT QUARANTINE_FACILITY_FK_DOCTOR_ID FOREIGN KEY (DOCTOR_ID) REFERENCES USERS(USER_ID)
    )
    ')]';
EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('QUARANTINED_PATIENT_DETAILS','CREATE TABLE QUARANTINED_PATIENT_DETAILS
            (
             QUARANTINED_PATIENT_DETAILS_ID NUMBER(10),
	    QUARANTINE_FACILITY_ID NUMBER(10) NOT NULL,  
             USER_ID NUMBER(20) NOT NULL, 
             JOIN_DATE DATE NOT NULL,
             CONSTRAINT QUARANTINED_PATIENT_DETAILS_PK PRIMARY KEY(QUARANTINED_PATIENT_DETAILS_ID),
	CONSTRAINT QUARANTINED_PATIENT_DETAILS_FK_FACILITY_ID FOREIGN KEY (QUARANTINE_FACILITY_ID) REFERENCES QUARANTINE_FACILITY(QUARANTINE_FACILITY_ID),
CONSTRAINT QUARANTINED_PATIENT_DETAILS_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
    )
    ')]';
EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('TEST_SCHEDULE','CREATE TABLE TEST_SCHEDULE
            (
             TEST_SCHEDULE_ID NUMBER(10),
	    USER_ID NUMBER(10) NOT NULL,  
             TEST_DATE DATE NOT NULL, 
             TEST_SLOT_ID  NUMBER(10) NOT NULL,
	CENTER_ID NUMBER(10) NOT NULL,
	TEST_TYPE_ID NUMBER(10) NOT NULL,
 	SCHEDULE_STATUS VARCHAR2(20) NOT NULL,
	TEST_RESULTS VARCHAR2(20),
             CONSTRAINT TEST_SCHEDULE_PK PRIMARY KEY(TEST_SCHEDULE_ID),
CONSTRAINT TEST_SCHEDULE_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
CONSTRAINT TEST_SCHEDULE_FK_TEST_SLOT_ID FOREIGN KEY (TEST_SLOT_ID) REFERENCES SLOTS(SLOT_ID),
CONSTRAINT TEST_SCHEDULE_FK_TEST_TYPE_ID FOREIGN KEY (TEST_TYPE_ID) REFERENCES TEST_TYPE(TEST_TYPE_ID)
    )
    ')]';
  
       
       EXECUTE IMMEDIATE q'[INSERT INTO CONFIG_TABLE VALUES ('USER_LOGIN_AUDIT','CREATE TABLE USER_LOGIN_AUDIT

             AUDIT_ID NUMBER(10), 
             USER_ID NUMBER(10),
             LOGIN_STATUS VARCHAR2(10) NOT NULL,
             AUDIT_DATE DATE NOT NULL,
             CONSTRAINT USER_LOGIN_AUDIT_PK PRIMARY KEY(AUDIT_ID),
             CONSTRAINT USER_LOGIN_AUDIT_FK_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ,
             CONSTRAINT USER_LOGIN_AUDIT_LOGIN_STATUS CHECK (LOGIN_STATUS IN (''login'',''logout''))
        )
      ')]';
         
    END IF;
END ;
/

DECLARE
  CURSOR config_table_cur
  IS
    SELECT 
        *
    FROM 
        config_table;
        
    tab_name varchar2(50);
    tab_def varchar2(3000);
    row_count number(10):= 0;
BEGIN
  FOR i IN config_table_cur
  LOOP
      tab_name:= i.table_name;
      tab_def:= i.table_def;
      
      DBMS_OUTPUT.PUT_LINE('tab_name -- '|| tab_name);
      DBMS_OUTPUT.PUT_LINE('--------------------------');

      SELECT count(*) into row_count FROM user_tables where table_name = tab_name;
       IF(row_count > 0)
        THEN
            DBMS_OUTPUT.PUT_LINE('TABLE '|| tab_name || ' ALREADY EXISTS');
        ELSE
            DBMS_OUTPUT.PUT_LINE('--------------------------');  
            EXECUTE IMMEDIATE tab_def;
            dbms_output.put_line( 'TABLE '|| tab_name || ' CREATED SUCCESSFULLY!' );
         END IF;
  END LOOP;
  dbms_output.put_line( 'ALL TABLES CREATED');
END;
/


CREATE SEQUENCE  "ADMIN"."LOGIN_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."SLOTS_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."TEST_AVAILABILITY_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."TEST_QPID_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."TEST_SCHEDULE_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."USER_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."LOCATION_SEQ"  START WITH 100  INCREMENT BY 1 ;
CREATE SEQUENCE  "ADMIN"."TEST_CENTER_SEQ"  START WITH 100  INCREMENT BY 1 ;


-------------------POPULATE TABLES-----------------

INSERT INTO LOCATION VALUES (1,'BOSTON','MA',02215);
INSERT INTO LOCATION VALUES (2,'NEW YORK','NY',10001);
INSERT INTO LOCATION VALUES (3,'CAMBRIDGE','MA',02114);
INSERT INTO LOCATION VALUES (4,'LOWELL','MA',01850);
INSERT INTO LOCATION VALUES (6,'SAN JOSE','CA',95119);
INSERT INTO LOCATION VALUES (7,'SAN FRANCISCO','CA',94105);
INSERT INTO LOCATION VALUES (8,'LOS ANGELES','CA',90001);


INSERT INTO TEST_TYPE VALUES (1, 'COVID - PCR');
INSERT INTO TEST_TYPE VALUES (2, 'COVID - RT PCR');
INSERT INTO TEST_TYPE VALUES (3, 'COVID - ANTIGEN');

SELECT * FROM TEST_CENTER;

SELECT * FROM SLOTS;
SELECT SYSDATE FROM DUAL;



begin
INSERT INTO SLOTS VALUES (2, 'MORNING', TO_TIMESTAMP('25-APR-21 09', 'DD-MON-YY HH24'),10);
exception when others then
 dbms_output.put_line( 'duplicate entry supressed');
end;


----populate slots table----
INSERT INTO SLOTS VALUES 
(select 1, 'MORNING', TO_TIMESTAMP('25-APR-21 08', 'DD-MON-YY HH24'),10 
    from dual where not exists (select 1 from SLOTS where slot_id = 1 and slot_name = 'MORNING'
    and slot_time = TO_TIMESTAMP('25-APR-21 08', 'DD-MON-YY HH24') and slots_available = 10 ));

INSERT INTO SLOTS VALUES (2, 'MORNING', TO_TIMESTAMP('25-APR-21 09', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (3, 'MORNING', TO_TIMESTAMP('25-APR-21 10', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (4, 'MORNING', TO_TIMESTAMP('25-APR-21 11', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (5, 'MORNING', TO_TIMESTAMP('25-APR-21 12', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (6, 'MORNING', TO_TIMESTAMP('25-APR-21 14', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (7, 'MORNING', TO_TIMESTAMP('25-APR-21 15', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (8, 'MORNING', TO_TIMESTAMP('25-APR-21 16', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (9, 'MORNING', TO_TIMESTAMP('25-APR-21 17', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (10, 'MORNING', TO_TIMESTAMP('25-APR-21 18', 'DD-MON-YY HH24'),10);

INSERT INTO SLOTS VALUES (11, 'MORNING', TO_TIMESTAMP('25-APR-21 09', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (12, 'MORNING', TO_TIMESTAMP('25-APR-21 09', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (13, 'MORNING', TO_TIMESTAMP('25-APR-21 10', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (14, 'MORNING', TO_TIMESTAMP('25-APR-21 11', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (15, 'MORNING', TO_TIMESTAMP('25-APR-21 12', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (16, 'MORNING', TO_TIMESTAMP('25-APR-21 14', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (17, 'MORNING', TO_TIMESTAMP('25-APR-21 15', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (18, 'MORNING', TO_TIMESTAMP('25-APR-21 16', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (19, 'MORNING', TO_TIMESTAMP('25-APR-21 17', 'DD-MON-YY HH24'),10);
INSERT INTO SLOTS VALUES (20, 'MORNING', TO_TIMESTAMP('25-APR-21 18', 'DD-MON-YY HH24'),10);



----populate TEST_AVAILIBILTY table----
INSERT INTO TEST_AVAILIBILTY VALUES(1, 10, 1, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(2, 10, 2, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(3, 10, 3, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(4, 10, 4, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(5, 10, 5, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(6, 10, 6, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(7, 10, 7, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(8, 10, 8, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(9, 10, 9, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(10, 10, 10, 1);

INSERT INTO TEST_AVAILIBILTY VALUES(11, 10, 11, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(12, 10, 12, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(13, 10, 13, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(14, 10, 14, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(15, 10, 15, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(16, 10, 16, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(17, 10, 17, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(18, 10, 18, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(19, 10, 19, 1);
INSERT INTO TEST_AVAILIBILTY VALUES(20, 10, 20, 1);


--alter session set nls_date_format='DD-MON-RR';
--INSERT INTO SLOTS VALUES (SLOTS_SEQ.NEXTVAL, 'MORNING', TO_TIMESTAMP('25-APR-21 15', 'DD-MON-YY HH24'),10);


